name: PR Review Check and Deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  add-reviewers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      env:
        REPO: ${{ github.repository }} 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh auth login --with-token  # Authenticate with the token
        unset GH_TOKEN  # Clear the token after authentication

    - name: Assign reviewers from CODEOWNERS
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        REPO=${{ github.repository }}
        gh pr review-request $PR_NUMBER --repo $REPO

    - name: Verify assigned reviewers
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        REPO=${{ github.repository }}
        gh pr view $PR_NUMBER --repo $REPO --json reviewRequests --jq '.reviewRequests.nodes'

  check-approval:
    runs-on: ubuntu-latest
    needs: add-reviewers
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      env:
        REPO: ${{ github.repository }} 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh auth login --with-token  # Authenticate with the token
        unset GH_TOKEN  # Clear the token after authentication

    - name: Check for PR approval
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        REPO=${{ github.repository }}
        REVIEWS=$(gh pr reviews $PR_NUMBER --repo $REPO --json state --jq '.[] | select(.state == "APPROVED")')

        if [[ -z "$REVIEWS" ]]; then
          echo "PR has not been approved by required reviewers."
          exit 1
        else
          echo "PR approved by required reviewers."
        fi

  prod-deploy:
    runs-on: ubuntu-latest
    needs: check-approval
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build and deploy
      run: |
        npm run build
        npm run deploy
