name: Add Reviewers on PR Opened or Edited

on:
  pull_request:
    types: [opened, edited]  # Trigger on pull request opened or edited

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewers
        id: add_reviewers
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use the GitHub token for authentication
          REPO: ${{ github.repository }}              # Repository name
          PR_NUMBER: ${{ github.event.pull_request.number }}  # Pull request number
        run: |
          # Define the reviewers you want to add
          REVIEWERS=("pathania25" "manasa-telus")

          # Make API call to add reviewers
          response=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/requested_reviewers" \
            -d "{\"reviewers\": [\"${REVIEWERS[@]}\"]}")

          # Output the response for debugging
          echo "Response from adding reviewers: $response"

      - name: Check for Required Approvals
        run: |
          # Fetch pull request details to check for reviewers' approval
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER")

          # Extract approvals
          approvals=$(echo "$response" | jq -r '.reviews | map(select(.state=="APPROVED")) | map(.user.login) | .[]')

          # Convert the environment variable GITHUB_REVIEWERS into an array
          IFS=',' read -r -a required_reviewers <<< "${{ secrets.GITHUB_REVIEWERS }}"
          missing_approvals=()

          # Check if required reviewers have approved
          for reviewer in "${required_reviewers[@]}"; do
            if [[ ! " ${approvals[@]} " =~ " ${reviewer} " ]]; then
              missing_approvals+=("$reviewer")
            fi
          done

          if [ ${#missing_approvals[@]} -ne 0 ]; then
            echo "The following required reviewers have not approved: ${missing_approvals[*]}"
            exit 1  # Fail the job if any required reviewers have not approved
          else
            echo "All required reviewers have approved."
          fi
