name: Add Reviewers on PR Events

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add Reviewers
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use the GitHub token for authentication
          REPO: ${{ github.repository }}              # Repository name
          PR_NUMBER: ${{ github.event.pull_request.number }}  # Pull request number
          GITHUB_REVIEWERS: ${{ secrets.REVIEWERS }}  # Accessing the reviewers' secret
        run: |
          # Make API call to add reviewers
          response=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/requested_reviewers" \
            -d "{\"reviewers\": [${GITHUB_REVIEWERS}]}")
          
          # Output the response for debugging
          echo "Response from adding reviewers: $response"
