name: Pull Request Review Process

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Check for assigned reviewers via CODEOWNERS
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          curl -s -H "Authorization: token $TOKEN" \
          "https://api.github.com/repos/${REPO}/pulls/${{ github.event.pull_request.number }}" | jq '.requested_reviewers'

  check-approval:
    runs-on: ubuntu-latest
    needs: add-reviewers  # This ensures that check-approval only runs after add-reviewers job

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Check approval status
        run: |
          APPROVAL_COUNT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" | jq '[.[] | select(.state == "APPROVED")] | length')
          if [ "$APPROVAL_COUNT" -lt 1 ]; then
            echo "PR has not been approved by the required reviewers."
            exit 1
          else
            echo "PR has been approved by at least one reviewer."
          fi
  
  deploy:
    needs: check-approval  # Ensure this job runs only after approval checks
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: |
          echo "Deploying to production"              
                  
