name: PR Review Check and Deployment

on:
  pull_request:
    branches:
      - main  # Trigger when a PR is created or updated for the `main` branch
  push:
    branches:
      - main  # Trigger deployment when the PR is merged into the main branch

jobs:
  add-reviewers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh auth login --with-token
        unset GH_TOKEN  
        
    - name: Assign reviewers from CODEOWNERS
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        REPO=${{ github.repository }}
        gh pr review-request $PR_NUMBER --repo $REPO

    - name: Verify assigned reviewers
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        REPO=${{ github.repository }}
        gh pr view $PR_NUMBER --repo $REPO --json reviewRequests --jq '.reviewRequests.nodes'

  check-approval:
    runs-on: ubuntu-latest
    needs: add-reviewers  # Ensure this job runs after adding reviewers
    if: github.event.pull_request.merged == true  # Only run if the PR is merged

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh auth login --with-token
        unset GH_TOKEN  # Clear the token from the environment to avoid reuse

    - name: Check for PR approval
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        REPO=${{ github.repository }}
        REVIEWS=$(gh pr reviews $PR_NUMBER --repo $REPO --json state --jq '.[] | select(.state == "APPROVED")')

        if [[ -z "$REVIEWS" ]]; then
          echo "PR has not been approved by required reviewers."
          exit 1
        else
          echo "PR approved by required reviewers."
        fi

  prod-deploy:
    runs-on: ubuntu-latest
    needs: check-approval  # Only deploy after PR approval is verified
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only deploy on push to main

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install  # Adjust this for your specific build system

    - name: Build and deploy
      run: |
        echo "Deploying to Production"
