name: Add Reviewers on PR Events

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Reviewers and Add Reviewers
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # GitHub token for authentication
          REPO: ${{ github.repository }}               # Dynamic repository name (e.g., pathania25/workflow_demo)
          PR_NUMBER: ${{ github.event.pull_request.number }}  # Pull request number
          GITHUB_REVIEWERS: pathania25,manasa-telus  # Comma-separated reviewer usernames
        run: |
          # Convert the comma-separated GITHUB_REVIEWERS into a JSON array
          REVIEWERS_ARRAY=$(echo "$GITHUB_REVIEWERS" | tr ',' '\n' | jq -R . | jq -s .)

          # Make sure the REVIEWERS_ARRAY is correctly formed
          echo "Reviewers Array: $REVIEWERS_ARRAY"

          # Make API call to add reviewers
          response=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/requested_reviewers" \
            -d "{\"reviewers\": $REVIEWERS_ARRAY}")

          # Output the response for debugging
          echo "Response from adding reviewers: $response"

          # Check if the API call was successful
          if [[ $(echo "$response" | jq -r '.message') != null ]]; then
            echo "Error: ${response}"
            exit 1  # Fail the job if adding reviewers failed
          else
            echo "Reviewers added successfully."
          fi
