name: Apply Branch Protection Rules

on:
  push:
    branches:
      - main

jobs:
  apply-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Protection Rule on main
        run: |
          gh api --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/branches/main/protection \
            -f enforce_admins=true \
            -f required_status_checks='{"strict": true, "contexts": []}' \
            -f required_pull_request_reviews='{"dismiss_stale_reviews": false, "require_code_owner_reviews": true, "required_approving_review_count": 2}' \
            -f restrictions='{"users": [], "teams": []}' \
            -f allow_force_pushes=false \
            -f allow_deletions=false
