name: Update GitHub Settings

on:
  push:
    branches:
      - main

jobs:
  update-settings:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up GitHub CLI
      uses: cli/cli@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Apply Branch Protection Rules
      run: |
        gh api --method PUT \
          -H "Accept: application/vnd.github.v3+json" \
          /repos/${{ github.repository }}/branches/main/protection \
          -f required_status_checks='{"strict": true, "contexts": []}' \
          -f enforce_admins=true \
          -f required_pull_request_reviews='{"dismiss_stale_reviews": false, "require_code_owner_reviews": true, "required_approving_review_count": 1}' \
          -f restrictions='{"users": [], "teams": []}' \
          -f allow_force_pushes=false \
          -f allow_deletions=false

    - name: Confirm Branch Protection
      run: |
        echo "Checking branch protection rules for 'main' branch..."
        gh api /repos/${{ github.repository }}/branches/main/protection
