name: Setup Branch Protection Rules

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main 
      - '*'     

jobs:
  set-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
              
      - name: Configure Branch Protection
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
        run: |
          REPO=${{ github.repository }}
          BRANCH="main"
          REQUIRED_APPROVALS=1
          
          # Set branch protection rules using GitHub API
          curl -X PUT \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/{REPO}/branches/{BRANCH}/protection \
          -d '{
            "required_status_checks": null,
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": true,
              "required_approving_review_count": $REQUIRED_APPROVALS
            },
            "restrictions": {
              "users": [],
              "teams": []
            }
            "allow_force_pushes":False,
            "allow_deletions":False 
          }'