name: PR Review Check and Deployment

on:
  pull_request:
    branches:
      - main  # Trigger when a PR is created or updated for the `main` branch
  push:
    branches:
      - main  # Trigger deployment when the PR is merged into the main branch

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

    - name: List files in .github directory (for debugging)
      run: |
        ls -al .github

    - name: Extract reviewers from CODEOWNERS
      id: extract-reviewers
      run: |
        # Path to the CODEOWNERS file
        CODEOWNERS_PATH=".github/CODEOWNERS"
        if [ -f "$CODEOWNERS_PATH" ]; then
          # Extract the reviewers from the CODEOWNERS file
          REVIEWERS=$(grep -v '^#' "$CODEOWNERS_PATH" | awk '{print $NF}' | sort | uniq | tr '\n' ',' | sed 's/,$//')
          echo "REVIEWERS=$REVIEWERS" >> $GITHUB_ENV
        else
          echo "CODEOWNERS file not found!"
          exit 1
        fi

    - name: Assign reviewers from CODEOWNERS to the PR
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        REPO=${{ github.repository }}
        REVIEWERS=${{ env.REVIEWERS }}
        if [ -z "$REVIEWERS" ]; then
          echo "No reviewers found in CODEOWNERS."
          exit 1
        else
          gh pr edit $PR_NUMBER --repo $REPO --add-reviewer $REVIEWERS
        fi

  check-approval:
    runs-on: ubuntu-latest
    needs: assign-reviewers
    if: github.event.pull_request.merged == true  # Only run if the PR is merged

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

    - name: Check for PR approval
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        REPO=${{ github.repository }}
        APPROVED=$(gh pr reviews $PR_NUMBER --repo $REPO --json state --jq '.[] | select(.state == "APPROVED")')
        
        if [[ -z "$APPROVED" ]]; then
          echo "PR has not been approved by required reviewers."
          exit 1
        else
          echo "PR approved by required reviewers."
        fi

  prod-deploy:
    runs-on: ubuntu-latest
    needs: check-approval
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only deploy on push to main branch

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install  # Replace with your build command, e.g., yarn, etc.

    - name: Build and Deploy
      run: 
        echo "Deploy to prod"