name: PR Review Check and Deployment

on:
  pull_request:
    branches:
      - main  # Trigger when a PR is created or updated for the `main` branch
  push:
    branches:
      - main  # Trigger deployment when the PR is merged into the main branch

jobs:
  add-reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

          - name: Extract reviewers from CODEOWNERS
          id: extract-reviewers
          run: |
            # Extracting reviewers from the CODEOWNERS file
            CODEOWNERS_PATH=".github/CODEOWNERS"
            if [ -f "$CODEOWNERS_PATH" ]; then
              REVIEWERS=$(grep -v '^#' "$CODEOWNERS_PATH" | awk '{print $NF}' | sort | uniq | tr '\n' ',' | sed 's/,$//')
              echo "REVIEWERS=$REVIEWERS" >> $GITHUB_ENV
            else
              echo "CODEOWNERS file not found!"
              exit 1
            fi
    
      - name: Assign reviewers from CODEOWNERS
        run: |
           # Extracting the PR number and repository name
            PR_NUMBER=${{ github.event.pull_request.number }}
            REPO=${{ github.repository }}
    
            # Using reviewers from the CODEOWNERS file
            echo "Assigning reviewers for PR #${PR_NUMBER} in repository ${REPO}..."
            gh pr edit $PR_NUMBER --repo $REPO --add-reviewer ${{ env.REVIEWERS }}
    
      - name: Verify assigned reviewers
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          gh pr view $PR_NUMBER --repo $REPO --json reviewRequests --jq '.reviewRequests.nodes'

  check-approval:
    runs-on: ubuntu-latest
    needs: add-reviewers  # Ensure this job runs after adding reviewers
    if: github.event.action == 'closed' && github.event.pull_request.merged == true  # Only run if the PR is merged

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

      - name: Check for PR approval
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          REVIEWS=$(gh pr reviews $PR_NUMBER --repo $REPO --json state --jq '.[] | select(.state == "APPROVED")')

          if [[ -z "$REVIEWS" ]]; then
            echo "PR has not been approved by required reviewers."
            exit 1
          else
            echo "PR approved by required reviewers."
          fi

  prod-deploy:
    runs-on: ubuntu-latest
    needs: check-approval  # Only deploy after PR approval is verified
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only deploy on push to main

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # Adjust this for your specific build system

      - name: Build and deploy
        run: |
          npm run build
          npm run deploy  # Adjust this for your deployment command
