name: Deploy to Production

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
      
      # Step 2: Check for required reviewers
      - name: Check Required Reviewers
        id: require_reviewers
        run: |
          # Get the pull request number and repository
          PR_NUMBER=${{ github.event.number }}
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}

          # Fetch the pull request details
          response=$(curl -s -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER")
          
          # Extract requested reviewers and reviewers from the reviews API
            requested_reviewers=$(echo "$response" | jq -r '.requested_reviewers | map(.login) | .[]')

          # Fetch pull request reviews to check existing reviews
            reviews_response=$(curl -s -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/reviews")

          # Extract reviewers from reviews
            reviewed_users=$(echo "$reviews_response" | jq -r '.[].user.login')

          # Combine requested reviewers and reviewed users
            all_reviewers="$requested_reviewers"$'\n'"$reviewed_users"

          # Check if required reviewers are present
            required_reviewers=("pathania25" "manasa-telus" "ravicharan-nettyam")
            missing_reviewers=()

            for reviewer in "${required_reviewers[@]}"; do
              if ! echo "$all_reviewers" | grep -q "$reviewer"; then
               missing_reviewers+=("$reviewer")
             fi
          done

              if [ ${#missing_reviewers[@]} -ne 0 ]; then
              echo "The following required reviewers are missing: ${missing_reviewers[*]}"
                exit 1  # Fail the job if any required reviewers are not present
              else
              echo "All required reviewers are present."
              fi

  deploy:
    runs-on: ubuntu-latest
    needs: check-pr
    if: github.ref == 'refs/heads/main' # Ensure this job runs only on main branch
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: |
          echo "Deploying to production"
